[package]
name = "tyto"
version = "0.1.0"
authors = ["Alexander Decurnou <ad@alx.xyz>"]
edition = "2018"

[dependencies]
actix-web = "*"
bendy = "^0.2"
bytes = "*"
clap = "*"
config = "0.9"
env = "*"
log = "*"
parking_lot = "*"
percent-encoding = "*"
pretty_env_logger = "*"
raft-rs = "*"
rand = "*"
serde = { version = "1.0", features = ["derive", "rc"] }
url = "*"

[dependencies.hashbrown]
version = "*"
features = ["serde", "rayon"]
