# This is the network address and port to which Tyto
# will try to bind. This can be exposed on a server, but it's
# recommended that Tyto sit behind a web server or load balancer.
[network]
binding = '0.0.0.0:6666'

# These are the current backend options: mysql
# Path is either the database address or file path.
[storage]
backend = 'mysql'
path = 'mysql://ad@localhost/tyto_test'

# These are self-explanatory BitTorrent-specific options.
[bt]
announce_rate = 1800
peer_timeout = 7200
reap_interval = 1800
flush_interval = 900

# This is where one can control the ability of certain clients to
# interface with the tracker. Setting 'blacklist_style' to true will 
# allow for any client that is not part of the client list to interact
# with the tracker. Setting it to false will instead make the client 
# list function as a whitelist where only listed clients can interact.
#
# The client list can be comprised in a versionless way in which only
# the first two characters of the peer ID encode the client are used,
# or a versioned way in which the first six characters of the peer ID
# are used to denoted the client and version number. Please make sure
# that the list is consistent.
[client_approval]
enabled = false
blacklist_style = false
versioned = false
client_list = [
    "DE",
    "LT",
    "qB",
    "TR",
    "UT"
]
